# Generated by Django 4.2.7 on 2023-11-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packsystem', '0002_rename_user_packagesystemuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesystemuser',
            name='course',
        ),
    ]
