# Generated by Django 4.2.7 on 2023-11-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packsystem', '0003_remove_packagesystemuser_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
