# Generated by Django 4.2.7 on 2023-11-23 14:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('packsystem', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
